name: Run - Extractor

on:
  workflow_dispatch:
    inputs:
      CONFIGURATION_YAML_PATH:
        description: 'Choose Wether to extract all Apis or extract apis listed an extraction configuration file'     
        required: true
        type: choice
        options:
        - Extract All APIs
        - configuration.extractor.yaml
      API_SPECIFICATION_FORMAT:
        description: 'API Specification Format'     
        required: true
        type: choice
        options:
        - OpenAPIV3Yaml 
        - OpenAPIV3Json
        - OpenAPIV2Yaml
        - OpenAPIV2Json

env:
  apiops_release_version: v6.0.1.10

jobs:
  extract:
    runs-on: ubuntu-latest
    environment: dev # change this to match the dev environment created in settings 
    steps:
      - uses: actions/checkout@v4
          
      - name: Run extractor without Config Yaml
        if: ${{ github.event.inputs.CONFIGURATION_YAML_PATH == 'Extract All APIs' }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/apimartifacts  # change this to the artifacts folder
          API_SPECIFICATION_FORMAT: ${{ github.event.inputs.API_SPECIFICATION_FORMAT }} 
          # AZURE_CLOUD_ENVIRONMENT: AzureChinaCloud
        run: |
          set -euo pipefail

          echo "Setting name variables..."
          release_file_name="extractor-linux-x64.zip"
          executable_file_name="extractor"

          echo "Downloading release..."
          uri="https://github.com/Azure/apiops/releases/download/${{ env.apiops_release_version }}/${release_file_name}"
          download_file_path="${{ runner.temp }}/${release_file_name}"
          curl -fL "$uri" -o "$download_file_path"

          echo "Extracting release..."
          executable_folder_path="${{ runner.temp }}/extractor"
          rm -rf "$executable_folder_path"
          mkdir -p "$executable_folder_path"
          unzip -oq "$download_file_path" -d "$executable_folder_path"
          executable_file_path="${executable_folder_path}/${executable_file_name}"

          echo "Setting file permissions..."
          chmod +x "$executable_file_path"

          echo "Running extractor..."
          "$executable_file_path"

          echo "Execution complete."
        shell: bash
      
      - name: Run extractor with Config Yaml
        if: ${{ github.event.inputs.CONFIGURATION_YAML_PATH != 'Extract All APIs' }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/apimartifacts  # change this to the artifacts folder
          API_SPECIFICATION_FORMAT: ${{ github.event.inputs.API_SPECIFICATION_FORMAT }} 
          CONFIGURATION_YAML_PATH:  ${{ GITHUB.WORKSPACE }}/${{ github.event.inputs.CONFIGURATION_YAML_PATH }}
          # AZURE_CLOUD_ENVIRONMENT: AzureChinaCloud
        run: |
          set -euo pipefail

          echo "Setting name variables..."
          release_file_name="extractor-linux-x64.zip"
          executable_file_name="extractor"

          echo "Downloading release..."
          uri="https://github.com/Azure/apiops/releases/download/${{ env.apiops_release_version }}/${release_file_name}"
          download_file_path="${{ runner.temp }}/${release_file_name}"
          curl -fL "$uri" -o "$download_file_path"

          echo "Extracting release..."
          executable_folder_path="${{ runner.temp }}/extractor"
          rm -rf "$executable_folder_path"
          mkdir -p "$executable_folder_path"
          unzip -oq "$download_file_path" -d "$executable_folder_path"
          executable_file_path="${executable_folder_path}/${executable_file_name}"

          echo "Setting file permissions..."
          chmod +x "$executable_file_path"

          echo "Running extractor..."
          "$executable_file_path"

          echo "Execution complete."
        shell: bash

      - name: publish artifact
        uses: actions/upload-artifact@v4
        env:
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts  # change this to the artifacts folder  
        with:
          name: artifacts-from-portal
          path: ${{ GITHUB.WORKSPACE }}/${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}    
          
  create-pull-request:
    needs: extract
    runs-on: [ubuntu-latest]
    environment: dev # must match the environment where PAT_GITHUB_TOKEN is defined
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
          
      - name: Download artifacts-from-portal
        uses: actions/download-artifact@v4
        env:
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts  # change this to the artifacts folder  
        with:
          name: artifacts-from-portal
          path: "${{ GITHUB.WORKSPACE }}/${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}"

      - name: Create artifacts pull request
        uses: peter-evans/create-pull-request@v6
        env:
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts  # change this to the artifacts folder          
        with:
          token: ${{ secrets.PAT_GITHUB_TOKEN2 || github.token }}
          commit-message: "updated extract from apim instance ${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}"
          title: "${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }} - extract"
          body: >
            This PR is auto-generated by Github actions workflow
          labels: extract, automated pr      
